#pragma once

#define DRIVER_PREFIX "MAL_UNP_DRV: "

#define MY_DEVICE_NAME L"MalUnpackCompanion"

#define MY_DEVICE L"\\Device\\MalUnpackCompanion"
#define MY_DRIVER_LINK L"\\??\\MalUnpackCompanion"

struct ProcessDataBasic {
	ULONG Pid;
};

struct ProcessDataEx_v1 {
	ULONG Pid;
	LONGLONG fileId;
};

struct ProcessDataEx_v2 {
	ULONG Pid;
	LONGLONG fileId;
	ULONG noresp; //respawn protection level
};

typedef ProcessDataEx_v2 ProcessDataEx;


#define MUNPACK_COMPANION_DEVICE 0x8000

#define IOCTL_MUNPACK_COMPANION_VERSION CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_ADD_TO_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_TERMINATE_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_LIST_PROCESSES CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_LIST_FILES CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_REMOVE_FROM_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_COUNT_NODES CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
