#pragma once

#define DRIVER_PREFIX "MAL_UNP_DRV: "

#define MY_DEVICE_NAME L"MalUnpackCompanion"

#define MY_DEVICE L"\\Device\\MalUnpackCompanion"
#define MY_DRIVER_LINK L"\\??\\MalUnpackCompanion"

struct ProcessData {
	ULONG Id;
};

struct ProcessDataEx {
	ULONG Id;
	LONGLONG fileId;
};


#define MUNPACK_COMPANION_DEVICE 0x8000

#define IOCTL_MUNPACK_COMPANION_VERSION CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_ADD_TO_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_TERMINATE_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_LIST_PROCESSES CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_LIST_FILES CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MUNPACK_COMPANION_REMOVE_FROM_WATCHED CTL_CODE(MUNPACK_COMPANION_DEVICE, \
	0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
